estacion46/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
]

estacion46/estacion46/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from. import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.DashboardPage.as_view(), name='dashboard'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('inventario/', include('inventory_app.urls',namespace='inventario')),
    path('productos/', include('products.urls',namespace='productos')),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
]

estacion46/inventory_app/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.InventoryList.as_view(),name='all'),
    path('nuevo/', views.InventoryCreateView.as_view(),name='create_product_inv'),
    path('editar/<int:pk>', views.InventoryUpdateView.as_view(), name='edit'),
    path('borrar/<int:pk>', views.InventoryDeleteView.as_view(), name='delete'),
]

estacion46/products/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductList.as_view(),name='all'),
    path('nuevo/', views.ProductCreateView.as_view(),name='create_product'),
    path('editar/<int:pk>', views.ProductUpdateView.as_view(), name='edit'),
    path('borrar/<int:pk>', views.ProductDeleteView.as_view(), name='delete'),
]

estacion46/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

estacion46/inventory_app/models.py
from django.db import models
from django.urls import reverse
from products.models import Product

from django.contrib.auth import get_user_model
User = get_user_model()

class Inventory(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Product, on_delete=models.CASCADE)
    codigo = models.CharField(max_length=80)
    cantidad = models.IntegerField()
    fecha_Ingreso = models.DateField(auto_now=True)

    def __str__(self):
        return self.producto

    def get_absolute_url(self):
        return reverse('inventory:all')

estacion46/products/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

class Product(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=80,unique=True)
    codigo = models.CharField(max_length=80)
    codigo_Interno = models.CharField(max_length=80,unique=True)
    presentacion = models.CharField(max_length=80)
    precio_Ingreso= models.FloatField()
    precio_Venta = models.FloatField()
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('products:all')

estacion46/inventory_app/forms.py
from .models import Inventory
from bootstrap_modal_forms.forms import BSModalForm

class InventoryForm(BSModalForm):

    class Meta:
        model = Inventory
        exclude = ['fecha_Ingreso']

estacion46/products/forms.py
from .models import Product
from bootstrap_modal_forms.forms import BSModalForm

class ProductForm(BSModalForm):

    class Meta:
        model = Product
        exclude = ['fecha']

estacion46/accounts/views.py
from django.shortcuts import render

# Create your views here.

estacion46/estacion46/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def HomePage(request):
     return HttpResponseRedirect(reverse('dashboard'))

class DashboardPage(LoginRequiredMixin,TemplateView):
    template_name = 'dashboard.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

estacion46/inventory_app/views.py
from django.shortcuts import render, get_object_or_404,get_object_or_404,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.contrib import messages
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from bootstrap_modal_forms.generic import (BSModalCreateView,
                                            BSModalUpdateView,
                                            BSModalDeleteView)

from .forms import InventoryForm

from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

class InventoryList(LoginRequiredMixin,generic.ListView):
    model = models.Inventory
    context_object_name = 'products_inv'

class InventoryCreateView(BSModalCreateView):
    model = models.Inventory
    form_class = InventoryForm
    template_name = 'inventory_app/inventory_form.html'
    success_url = reverse_lazy('inventory:all')

class InventoryUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = models.Inventory
    form_class = InventoryForm
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('inventory:all')

class InventoryDeleteView(LoginRequiredMixin,BSModalDeleteView):
    model = models.Inventory
    template_name = 'inventory/inventory_confirm_delete.html'
    success_message = 'Success: Inventory was deleted.'
    success_url = reverse_lazy('inventory:all')

estacion46/products/views.py
from django.shortcuts import render, get_object_or_404,get_object_or_404,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from bootstrap_modal_forms.generic import (BSModalCreateView,
                                            BSModalUpdateView,
                                            BSModalDeleteView)
from .forms import ProductForm

from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

class ProductList(LoginRequiredMixin,generic.ListView):
    model = models.Product
    context_object_name = 'products'

class ProductCreateView(BSModalCreateView):
    template_name = 'products/create_product.html'
    form_class = ProductForm
    success_url = reverse_lazy('products:all')

class ProductUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = models.Product
    form_class = ProductForm
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('products:all')

class ProductDeleteView(LoginRequiredMixin,BSModalDeleteView):
    model = models.Product
    template_name = 'products/product_confirm_delete.html'
    success_message = 'Success: Product was deleted.'
    success_url = reverse_lazy('products:all')

estacion46/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
  <title>Ingreso New OTRS</title>
{% endblock %}

{% block content %}
  <h1>
    <div class="register-title">
      ESTACIÓN 46
    </div>
  </h1>
  <form action="{% url 'login' %}" method="POST" class="register">
    {% csrf_token %}
    <input type="text" name='username' class="register-input" id="id_username" placeholder="Usuario">
    <input type="password" name='password' class="register-input" id="id_password" placeholder="Contraseña">
    <input type="submit" class="btn register-button" value="Ingresar">
  </form>
{% endblock %}

estacion46/inventory_app/templates/inventory_app/inventory_confirm_delete.html
<form method="POST" action="">
  {% csrf_token %}
  <div class="modal-header">
  <h3 class="modal-title">Borrar Producto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="jumbotron">
      <p>Estas seguro de borrar
        <strong>{{ product.nombre }}, {{ product.codigo_Interno }}</strong>?</p>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Borrar</button>
      </div>
    </div>
  </div>
</form>

estacion46/inventory_app/templates/inventory_app/inventory_form.html
<form method="post" action="">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Nuevo Ingreso</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="jumbotron">
      <h1 class="display-4">Nueva Entrada</h1>
      <hr class="my-4">
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <input type="text" class="form-control" readonly name="user" id="id_user" value="{{ user.id }}">
        </div>
      </div>
      <div class="form-group{% if form.user.errors %} invalid{% endif %}">
      {% for error in form.user.errors %}
        <p>{{ error }}</p>
      {% endfor %}
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <input type="text" class="form-control" required name="producto" id="id_producto" placeholder="Producto">
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group{% if form.user.errors %} invalid{% endif %}">
        {% for error in form.user.errors %}
          <p>{{ error }}</p>
        {% endfor %}
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-6">
          <input type="text" class="form-control" required name="codigo" id="id_codigo" placeholder="Codigo">
        </div>
        <div class="col-sm-6">
          <input type="text" class="form-control" required name="cantidad" id="id_cantidad" placeholder="Cantidad">
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group{% if form.codigo.errors %} invalid{% endif %}">
          {% for error in form.codigo.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group{% if form.cantidad.errors %} invalid{% endif %}">
          {% for error in form.cantidad.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Crear</button>
  </div>
</form>

estacion46/inventory_app/templates/inventory_app/inventory_list.html
{% extends "base.html" %}

{% block title %}
  <title>Inventario</title>
{% endblock %}

{% block breadcrumb %}Inventario{% endblock %}

{% block content %}
<button type="button" class="create-product_inv btn btn-primary" name="button">
  Agregar
</button>
<p></p>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Producto</th>
        <th scope="col">Codigo</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Fecha de Ingreso</th>
        <th scope="col">Usuario</th>
        <th colspan="2" scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for inventory in products_inv %}
      <tr>
        <th scope="row">{{ inventory.id }}</th>
        <td>{{ inventory.producto }}</td>
        <td>{{ inventory.codigo }}</td>
        <td>{{ inventory.cantidad }}</td>
        <td>{{ inventory.fecha_Ingreso }}</td>
        <td>{{ inventory.user}}</td>
        <td>
          <button type="button" class="update-product btn btn-sm btn-outline-info" data-id="{% url 'inventory:edit' inventory.pk %}">Editar</button>
          <button type="button" class="delete-product btn btn-sm btn-outline-danger" data-id="{% url 'inventory:delete' inventory.pk %}">Borrar</button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

{% endblock %}

{% block extrajs %}
<script type="text/javascript">

  $(function() {
       // Create product button
    $(".create-product_inv").modalForm({formURL: "{% url 'inventory:create_product_inv' %}"});

     // Update product buttons
    $(".update-product").each(function () {
      $(this).modalForm({formURL: $(this).data('id')});
    });

    // Delete product buttons
    $(".delete-product").each(function () {
      $(this).modalForm({formURL: $(this).data('id')});
    });

  });

</script>
{% endblock extrajs %}

{% block footer %}{% endblock %}

estacion46/inventory_app/templates/inventory_app/inventory_update_form.html
{% extends "base.html" %}

{% block title %}
  <title>Actualizar</title>
{% endblock %}

{% block precontent %}{% endblock %}

{% block content %}
<div class="jumbotron">
  <form method="post">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <div class="form-group row">
       <label for="id_email" class="col-sm-2 col-form-label">Email</label>
       <div class="col-sm-10">
         <input type="email" name="email" maxlength="254" class="form-control" id="id_email" required value="{{ client.email }}">
       </div>
     </div>
     <div class="form-group row">
       <div class="col-sm-10">
         <input type="submit" value="Actualizar" class="btn btn-primary btn-large">
       </div>
     </div>
  </form>
</div>
{% endblock %}

{% block footer %}{% endblock %}

estacion46/products/templates/products/create_product.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">Nuevo Ingreso</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <div class="jumbotron">
      <h1 class="display-6">Nueva Entrada</h1>
      <hr class="my-4">
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <input type="text" class="form-control" readonly name="user" id="id_user" value="{{ user.id }}">
        </div>
      </div>
      <div class="form-group{% if form.user.errors %} invalid{% endif %}">
      {% for error in form.user.errors %}
        <p>{{ error }}</p>
      {% endfor %}
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <input type="text" class="form-control" required name="nombre" id="id_nombre" placeholder="Producto">
        </div>
      </div>
      <div class="form-group{% if form.nombre.errors %} invalid{% endif %}">
      {% for error in form.nombre.errors %}
        <p>{{ error }}</p>
      {% endfor %}
      </div>
      <div class="form-group row">
        <div class="col-sm-4">
          <input type="text" class="form-control" required name="codigo" id="id_codigo" placeholder="Codigo">
        </div>
        <div class="col-sm-4">
          <input type="text" class="form-control" required name="codigo_Interno" id="id_codigo_Interno" placeholder="Cod. Interno">
        </div>
        <div class="col-sm-4">
          <input type="text" class="form-control" required name="presentacion" id="id_presentacion" placeholder="Presentación">
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group{% if form.codigo.errors %} invalid{% endif %}">
        {% for error in form.codigo.errors %}
          <p>{{ error }}</p>
        {% endfor %}
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group{% if form.codigo_Interno.errors %} invalid{% endif %}">
        {% for error in form.codigo_Interno.errors %}
          <p>{{ error }}</p>
        {% endfor %}
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group{% if form.presentacion.errors %} invalid{% endif %}">
        {% for error in form.presentacion.errors %}
          <p>{{ error }}</p>
        {% endfor %}
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-6">
          <input type="text" class="form-control" required name="precio_Ingreso" id="id_precio_Ingreso" placeholder="Precio Ingreso">
        </div>
        <div class="col-md-6">
          <input type="text" class="form-control" required name="precio_Venta" id="id_precio_Venta" placeholder="Precio Venta">
        </div>
      </div>
      <div class="col-md-6">
        <div class="{% if form.precio_Ingreso.errors %} invalid{% endif %}">
        {% for error in form.precio_Ingreso.errors %}
          <li>{{ error }}</li>
        {% endfor %}
        </div>
      </div>
      <div class="col-md-6">
        <div class="{% if form.precio_Venta.errors %} invalid{% endif %}">
        {% for error in form.precio_Venta.errors %}
          <li>{{ error }}</li>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Crear</button>
  </div>
</form>

estacion46/products/templates/products/product_confirm_delete.html
<form method="POST" action="">
  {% csrf_token %}
  <div class="modal-header">
  <h3 class="modal-title">Borrar Producto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="jumbotron">
      <p>Estas seguro de borrar
        <strong>{{ product.nombre }}, {{ product.codigo_Interno }}</strong>?</p>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Borrar</button>
      </div>
    </div>
  </div>
</form>

estacion46/products/templates/products/product_list.html
{% extends "base.html" %}

{% block title %}
  <title>Listado Productos</title>
{% endblock %}

{% block breadcrumb %}Productos{% endblock %}

{% block content %}
<button type="button" class="create-product btn btn-primary" name="button" >
  Agregar
</button>
<p></p>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Producto</th>
      <th scope="col">Codigo</th>
      <th scope="col">Codigo Interno</th>
      <th scope="col">Presentación</th>
      <th scope="col">Precio entrada</th>
      <th scope="col">Precio venta</th>
      <th scope="col">Fecha de Ingreso</th>
      <th scope="col">Usuario</th>
      <th colspan="2" scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
      <th scope="row">{{ product.id }}</th>
      <td>{{ product.nombre }}</td>
      <td>{{ product.codigo }}</td>
      <td>{{ product.codigo_Interno }}</td>
      <td>{{ product.presentacion }}</td>
      <td>{{ product.precio_Ingreso }}</td>
      <td>{{ product.precio_Venta }}</td>
      <td>{{ product.fecha|date:"SHORT_DATE_FORMAT" }}</td>
      <td>{{ product.user }}</td>
      <td>
        <button type="button" class="update-product btn btn-sm btn-outline-info" data-id="{% url 'products:edit' product.pk %}">Editar</button>
        <button type="button" class="delete-product btn btn-sm btn-outline-danger" data-id="{% url 'products:delete' product.pk %}">Borrar</button>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

{% endblock %}

{% block extrajs %}
<script type="text/javascript">

  $(function() {
       // Create product button
    $(".create-product").modalForm({formURL: "{% url 'products:create_product' %}"});

     // Update product buttons
    $(".update-product").each(function () {
      $(this).modalForm({formURL: $(this).data('id')});
    });

    // Delete product buttons
    $(".delete-product").each(function () {
      $(this).modalForm({formURL: $(this).data('id')});
    });

  });

</script>
{% endblock extrajs %}

{% block footer %}{% endblock %}

estacion46/products/templates/products/product_update_form.html
<form method="POST" action="{% url 'products:edit' pk=product.pk %}">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Modificar</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="jumbotron">
      <h1 class="display-6">Modificar</h1>
      <hr class="my-4">
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <input type="text" class="form-control" readonly name="user" id="id_user" value="{{ user.id }}">
        </div>
      </div>
      <div class="form-group{% if form.user.errors %} invalid{% endif %}">
      {% for error in form.user.errors %}
        <p><strong>{{ error }}</strong></p>
      {% endfor %}
    </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <input type="text" class="form-control" required name="nombre" id="id_nombre" placeholder="Producto" value="{{ product.nombre }}">
        </div>
      </div>
      <div class="form-group{% if form.nombre.errors %} invalid{% endif %}">
      {% for error in form.nombre.errors %}
        <p><strong>{{ error }}</strong></p>
      {% endfor %}
      </div>
      <div class="form-group form-row">
        <div class="col-sm-4">
          <input type="text" class="form-control" required name="codigo" id="id_codigo" placeholder="Codigo" value="{{ product.codigo }}">
        </div>
        <div class="col-sm-4">
          <input type="text" class="form-control" readonly name="codigo_Interno" id="id_codigo_Interno" placeholder="Cod. Interno" value="{{ product.codigo_Interno }}">
        </div>
        <div class="col-sm-4">
          <input type="text" class="form-control" required name="presentacion" id="id_presentacion" placeholder="Presentación" value="{{ product.presentacion }}">
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group{% if form.codigo.errors %} invalid{% endif %}">
        {% for error in form.codigo.errors %}
          <p><strong>{{ error }}</strong></p>
        {% endfor %}
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group{% if form.codigo_Interno.errors %} invalid{% endif %}">
        {% for error in form.codigo_Interno.errors %}
          <p><strong>{{ error }}</strong></p>
        {% endfor %}
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group{% if form.presentacion.errors %} invalid{% endif %}">
        {% for error in form.presentacion.errors %}
          <p><strong>{{ error }}</strong></p>
        {% endfor %}
        </div>
      </div>
      <div class="form-group form-row">
        <div class="col-sm-6">
          <input type="text" class="form-control" required name="precio_Ingreso" id="id_precio_Ingreso" placeholder="Precio Ingreso" value="{{ product.precio_Ingreso}}">
        </div>
        <div class="col-md-6">
          <input type="text" class="form-control" required name="precio_Venta" id="id_precio_Venta" placeholder="Precio Venta" value="{{ product.precio_Venta }}">
        </div>
      </div>
      <div class="col-md-6">
        <div class="{% if form.precio_Ingreso.errors %} invalid{% endif %}">
        {% for error in form.precio_Ingreso.errors %}
          <li><strong>{{ error }}</strong></li>
        {% endfor %}
        </div>
      </div>
      <div class="col-md-6">
        <div class="{% if form.precio_Venta.errors %} invalid{% endif %}">
        {% for error in form.precio_Venta.errors %}
          <li><strong>{{ error }}</strong></li>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
    <input type="submit" value="Editar" class="submit-btn btn btn-primary">
  </div>  
</form>

estacion46/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% block title %}
      <title>Estación 46</title>
    {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <link rel="stylesheet" href="{% static 'estacion46/css/master.css' %}">
  </head>
  <body>
    {% block precontent %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a href="{% url 'dashboard' %}" class='navbar-brand'><img class="logo" src="{% static 'estacion46/images/logo estacion46.jpg' %}" alt=""></a>
        {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'products:all' %}"><button type="button" class="btn btn-outline-info">Productos</button></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'inventory:all' %}"><button type="button" class="btn btn-outline-info">Inventario</button></a></li>
          </ul>
          <a class="nav-link text-warning"><h5>Bienvenido: @{{ user.username }}</h5></a>
          <form action="#" method="GET" class="form-inline">
            <div class="input-group">
              <input type="text" name='q' class="form-control border-success" type="search" placeholder="" aria-label="Search" aria-describedby="button-addon2">
              <div class="input-group-append">
                <button class="btn btn-outline-success mr-sm-2" type="submit" id="button-addon2">Buscar</button>
              </div>
            </div>
            <!-- <button class="btn btn-outline-success my-2 mr-sm-2" type="submit">Buscar</button> -->
          </form>
          <a href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-outline-danger">Salir</button></a>
        {% else %}
          <!-- <ul class="navbar-nav mr-auto"></ul>
          <a href="#"><button type="button" class="btn btn-outline-primary my-2 my-sm-0 mr-sm-2">Log In</button></a> -->
        {% endif %}
      </div>
    </nav>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">{% block breadcrumb %}{% endblock %}</li>
      </ol>
    </nav>
    {% endblock %}

    <div class="container">
      <p></p>
      {% block content %}

      {% endblock %}
    </div>
    <canvas id="canvas"></canvas>
    <script type="text/javascript" src="{% static 'static/js/master.js' %}"></script>
    {% block extrajs %}
    {% endblock extrajs %}
  </body>
</html>

estacion46/templates/dashboard.html
{% extends "base.html" %}
{% block title %}
<title>Dashboard</title>
{% endblock %}
{% block content %}
<h2>Estadisticas</h2>
{% endblock %}
{% block footer %}{% endblock %}

estacion46/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}